---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    - name: post_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves comments of a post
      responses:
        '200':
          description: comments retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/definitions/comment"
    post:
      summary: Creates a comment
      parameters: []
      responses:
        '200':
          description: comment created
          content:
            application/json:
              schema:
                "$ref": "#/definitions/comment"
        '422':
          description: invalid comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/v1/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves posts of a user
      responses:
        '200':
          description: posts retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/definitions/post"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost
